name: CI for Pull Requests

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' # Use 'temurin' for OpenJDK

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test

      - name: Run JaCoCo Code Coverage
        run: mvn jacoco:report

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco/

      - name: Post Coverage Comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the coverage percentage
          coverage=$(grep -oP 'line rate</th>\s*<td>\K[0-9.]+(?=%)' target/site/jacoco/index.html)
          
          # Post comment on PR
          echo "Posting coverage results to PR..."
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -d "{\"body\": \"### JaCoCo Coverage Report\\nCoverage: ${coverage}%\"}" \
          "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${{ github.event.pull_request.number }}/comments"
